# Generated by Django 5.1.1 on 2024-11-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_mimodelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiModelo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='default@example.com', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
